- name: Deploy basic configs and services
  hosts: all
  become: true
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Debug
      ansible.builtin.debug:
        msg: "Var is {{ example_var }} and environment is {{ environment }}"
